chore: update kms settings for launch template to allow default kms (#1349)
## Description

Fix for change in `kms_key_id` validation on the launch template ebs
volumes. This was implemented on the aws provider 6.16.0
https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#6160-october-9-2025.
When using the default ebs kms key, it will now no longer complain about
the empty "" provided to the `kms_key_id` for ebs volumes with
encryption enabled.

> Error: "block_device_mappings.0.ebs.0.kms_key_id" cannot be shorter
than 1 character
> 
>   with module.runner.aws_launch_template.this[0],
> on .terraform/modules/runner/docker_machine_fleet.tf line 42, in
resource "aws_launch_template" "this":
>   41:       kms_key_id  = local.kms_key_arn
> 

Closes
https://github.com/cattle-ops/terraform-aws-gitlab-runner/issues/1348

Basically duplicate of
https://github.com/cattle-ops/terraform-aws-gitlab-runner/pull/1343 but
for docker_machine_fleet instead of docker_autoscaler.

Co-authored-by: Matthias Kay <matthias.kay@hlag.com>